/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "OurCan.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initCan();
    initCanDB();
    //    uint32 datas[2]={0x12340000,0x12340000};
    //    initMultican();
    while (1)
    {
        if (db_msg.TH_sensor.B.Flag == 1) // on message TH_sensor 느낌
        {                                 // ISR이 센서 값 받았다면.
            db_msg.TH_sensor.B.Flag = 0;  // 필수 처리!
            // 처리 로직 예시
            if (db_msg.TH_sensor.B.Temp_Hum_alive == 1)
            {                           // 받은 데이터의 Temp_Hum_alive 값이 1이라면
                OurCanACControl ACCmsg; // 에어컨 팬 컨트롤 로직을 수정하여
                ACCmsg.B.Air_fan_speed = 2;
                ACCmsg.B.Air_state = 1;
                output_message(&ACCmsg, AC_CONTROL_ID); // Can버스에 전송하는 예제

                // 예제를 수행하려면,
                // 1. OurCan_def.h 내부에 DB를 참고하여 동일한 형식으로 넣고,
                // 2. OurCan.h 내부에 DBMessages 안에 그 메시지를 선언해준다.
                // 3. 이후 원하는 로직 작성!
            }
        }
    }
}
