/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "OurCan.h"
#include "Driver_Stm.h"
#include "ASCLIN_Shell_UART.h"

typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;

} Taskcnt;

void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

Taskcnt stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    // CAN init
    initCan();
    initCanDB();

    // 스케쥴링 init
    Driver_Stm_Init();

    // Serial Debug용, 아직 미구현
    //    initSerialInterface();
    initShellInterface();

    while (1)
    {
        runShellInterface();
        AppScheduling();
        if (db_msg.TH_sensor.B.Flag == 1) // on message TH_sensor 느낌
        {                                 // ISR이 센서 값 받았다면.
            db_msg.TH_sensor.B.Flag = 0;  // 필수 처리!
            // 처리 로직 예시

            db_msg.smart_ac.B.Air_fan_speed = 2;
            output_message(&db_msg.smart_ac, SMART_AC_MSG_ID);
        }

        //        if(db_msg.motor1_window.B.Flag == 1){
        //            db_msg.motor1_window.B.Flag = 0;
        ////            db_msg.motor2_sunroof.B.motor2_alive = db_msg.motor1_window.B.motor1_alive;
        ////            db_msg.motor2_sunroof.B.motor2_running = db_msg.motor1_window.B.motor1_running;
        ////            db_msg.motor2_sunroof.B.motor2_tick_counter = db_msg.motor1_window.B.motor1_tick_counter;
        //
        //            output_message(&db_msg.motor1_window,MOTOR1_WINDOW_MSG_ID);
        //
        //        }
    }
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
    {
        //        //스케쥴링 예시코드 1ms 주기로 공기질 메시지 전송
        db_msg.out_air_quality.B.AQ_alive = 1;
        db_msg.out_air_quality.B.air_CO2 = 1024;
        db_msg.out_air_quality.B.air_CO = 584;
        db_msg.out_air_quality.B.air_NH4 = 10;
        db_msg.out_air_quality.B.air_alch = 1;
        output_message(&db_msg.out_air_quality, OUT_AIR_QUALITY_MSG_ID);
    }
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

    {
        //        //스케쥴링 예시코드 10ms 주기로 db 메시지 전송
        //        db_msg.db.B.db_alive = 1;
        //        db_msg.db.B.db_outside = 100;
        //        output_message(&db_msg.db, DB_MSG_ID);
    }
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    {
        //        //스케쥴링 예시코드 100ms 주기로 비 감지 메시지 전송
        //        db_msg.rain.B.raining_alive = 1;
        //        db_msg.rain.B.raining_status = 1;
        //        output_message(&db_msg.rain, RAIN_MSG_ID);
    }
}

void AppTask1000ms(void)
{

    stTestCnt.u32nuCnt1000ms++;
    {
        // 스케쥴링 예시코드 1000ms 주기로 광량 감지 메시지 전송
        //        db_msg.light.B.Light_alive =1;
        //        db_msg.light.B.Light_pct = stTestCnt.u32nuCnt1000ms%100;
        //        output_message(&db_msg.light, LIGHT_MSG_ID);
    }
}

void AppScheduling(void)
{

    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;

        AppTask1ms();

        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
