/**********************************************************************************************************************
 * \file queue.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "queue.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
QUEUE *queue_create()
{
    QUEUE *queue;
    queue = (QUEUE*)malloc(sizeof(QUEUE));

    queue->head = NULL;
    queue->tail = NULL;

    return queue;
}


boolean queue_isempty(QUEUE *q)
{
    if (q->head == NULL || q->tail == NULL)
    {
        return TRUE;
    }

    return FALSE;
}


void queue_enqueue(QUEUE *q, AudioControlState value)
{

    NODE *new_head_node = NULL;
    new_head_node = (NODE*)malloc(sizeof(NODE));

    new_head_node->value = value;
    new_head_node->prev = NULL;
    new_head_node->next = NULL;

    if(q->head == NULL)
    {
        q->head = new_head_node;
        q->tail = new_head_node;

        return;
    }

    q->head->prev = new_head_node;
    new_head_node->next = q->head;
    q->head = new_head_node;

    return;
}


void queue_dequeue(QUEUE *q, AudioControlState *value)
{
    NODE *old_tail_node;

    if (q->tail == NULL)
    {
        return;
    }

    old_tail_node = q->tail;


    *value = q->tail->value;
    q->tail = q->tail->prev;

    if (q->tail != NULL)
    {
        q->tail->next = NULL;
    }
    else
    {
        q->head = NULL;
    }

    free(old_tail_node);

    return;
}
/*********************************************************************************************************************/
