/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "Driver_Stm.h"
#include "Driver_Adc.h"
#include "Driver_Easy.h"
#include "Driver_Touch.h"
#include "Driver_Air.h"

#include "sound_sensor.h"
#include "rain_sensor.h"
#include "Driver_DHT11.h"

//GPIO related
#define PCn_2_IDX 19
#define P2_IDX 2
#define PCn_1_IDX 11
#define P1_IDX 1

// ERU related
#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11

// sensor related
#define AIR_PIN 4
#define LIGHT_PIN 6
#define R_PIN 7
#define SUN_TOUCH_PIN 0
#define WIN_TOUCH_PIN 1

typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;

}TestCnt;

// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);


/***********************************************************************/
/*Variable*/
/***********************************************************************/
TestCnt stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

float dB = 0.0f;
float maxdB = 0.0f;
boolean is_rain = FALSE;
uint32 rain_adc = 0.0f;
Gas gas_adc = { 0.0f, 0.0f,0.0f,0.0f,0.0f };
uint32 resist_adc = 0;
uint32 light_adc = 0;
IfxPort_State suntouch = 0;
IfxPort_State wintouch = 0;
Temp_Hum now_temp_hum = { 0,0,0,0,0 };
Temp_Hum now_status = { 0,0,0,0,0 };
int check = 0;
int check2 = 0;
int cnt1000=0;
int cnt100=0;
int cnt10=0;
int cnt1=0;

void initGPIO(void);
//void initERU(void);


int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGPIO();
    Driver_Stm_Init();
    init_led();
    init_gpio_touch(SUN_TOUCH_PIN);
    init_gpio_touch(WIN_TOUCH_PIN);
    init_sensor_driver(AIR_PIN); //Air
    init_sensor_driver(LIGHT_PIN); //Light
    init_sensor_driver(R_PIN); //Resistance


    init_sound_sensor();
    init_rain_sensor();
    cnt1000=0;
    cnt100=0;
    cnt10=0;
    cnt1=0;
    check2 = 0;
    now_status.flag = 0;
    now_status.huminityhigh = 0;
    now_status.huminitylow = 0;
    now_status.temperaturehigh = 0;
    now_status.temperaturelow = 0;
    while(1)
    {
        AppScheduling();
    }
    return (1);
}

void initGPIO(void){
    P02_IOCR0.U &= ~(0x1F << PCn_1_IDX);
    P02_IOCR0.U |= 0x02 << PCn_1_IDX;

    P10_IOCR0.U &= ~(0x1F << PCn_2_IDX);
    P10_IOCR0.U |= 0x10 << PCn_2_IDX;
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;

    cnt1++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
    cnt10++;
    gas_adc = get_air_condition();
    light_adc = get_light_condition();
    resist_adc= get_resist_condition();
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    cnt100++;
    suntouch = get_touch_condition(SUN_TOUCH_PIN);
    wintouch = get_touch_condition(WIN_TOUCH_PIN);
    dB = get_decibel();
    if (maxdB < dB) {
        maxdB = dB;
    }

    is_rain = is_raining();
    rain_adc = get_rain_sensor_analog_value();
}

void AppTask1000ms(void)
{
    cnt1000++;
    now_temp_hum = get_temp_hum();
    static int flag = 0;
    if(flag == 0)
    {
        IfxPort_setPinLow(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        flag = 1;
    }
    else
    {
        IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        flag = 0;
    }
    stTestCnt.u32nuCnt1000ms++;

}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
