/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"
#include "OurCan.h"
#include "Driver_Stm.h"
#include "Driver_Adc.h"
#include "Driver_Easy.h"
#include "Driver_Air.h"
#include "sound_sensor.h"
#include "rain_sensor.h"
#include "ASCLIN_Shell_UART.h"

#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11

// sensor related
#define AIR_PIN 4
#define LIGHT_PIN 6
#define R_PIN 7

typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;
}TestCnt;

// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);
/***********************************************************************/
/*Variable*/
/***********************************************************************/
TestCnt stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

float dB = 0.0f;
float maxdB = 0.0f;
boolean is_rain = FALSE;
uint32 rain_adc = 0.0f;
Gas gas_adc = { 0.0f, 0.0f,0.0f,0.0f,0.0f };
uint32 light_adc = 0;
boolean engine_on = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initCan();
    initCanDB();
    Driver_Stm_Init();

    init_sensor_driver(AIR_PIN); //Air
    init_sensor_driver(LIGHT_PIN); //Light
    init_sound_sensor(); //sound
    init_rain_sensor();  //rain

    while(1)
    {
        AppScheduling();
        if (db_msg.driver_engine.B.Flag == 1) // 시동 신호가 왔을 때
            {
                db_msg.driver_engine.B.Flag = 0;
                if (db_msg.driver_engine.B.engine_mode == 1 |db_msg.driver_engine.B.engine_mode == 2) // 시동 on or utility
                    engine_on = 1;
                else if (db_msg.driver_engine.B.engine_mode == 0) //시동 off
                    engine_on = 0;
            }
    }
    return (1);
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
    light_adc = get_light_condition();
    dB = get_decibel();
    if (maxdB < dB) {
        maxdB = dB;
    }
    db_msg.light.B.Light_pct = light_adc;
    if(engine_on==1)
        db_msg.light.B.Light_alive = 1;
    else if(engine_on==0)
        db_msg.light.B.Light_alive = 0;
    output_message(&db_msg.light, LIGHT_MSG_ID);
    db_msg.db.B.db_outside = dB;
    if(engine_on==1)
        db_msg.db.B.db_alive = 1;
    else if(engine_on==0)
        db_msg.db.B.db_alive = 0;

    output_message(&db_msg.db, DB_MSG_ID);
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    is_rain = is_raining();
    rain_adc = get_rain_sensor_analog_value();
    db_msg.rain.B.raining_status = is_rain;
    if(engine_on==1)
        db_msg.rain.B.raining_alive = 1;
    else if(engine_on==0)
        db_msg.rain.B.raining_alive = 0;
    output_message(&db_msg.rain, RAIN_MSG_ID);
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
    gas_adc = get_air_condition();
    db_msg.out_air_quality.B.air_CO2 = gas_adc.CO2;
    db_msg.out_air_quality.B.air_CO = gas_adc.CO;
    db_msg.out_air_quality.B.air_NH4 = gas_adc.NH4;
    db_msg.out_air_quality.B.air_alch = gas_adc.Alcohol;
    if(engine_on==1)
        db_msg.out_air_quality.B.AQ_alive = 1;
    else if(engine_on==0)
        db_msg.out_air_quality.B.AQ_alive = 0;
    output_message(&db_msg.out_air_quality, OUT_AIR_QUALITY_MSG_ID);
}


void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
