/**********************************************************************************************************************
 * \file queue.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "queue.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void init_queue(Queue *queue)
{
    queue->head = 0;
    queue->tail = 0;
    queue->size = 0;
}

// Queue가 비어 있는지 확인
boolean queue_isempty(Queue *queue)
{
    return (queue->size == 0);
}

// Queue가 가득 차 있는지 확인
boolean queue_isfull(Queue *queue)
{
    return (queue->size == QUEUE_MAX_SIZE);
}

// Queue에 데이터 삽입
void enqueue_queue(Queue *queue, AudioControlState value)
{
    if (queue_isfull(queue)) {
        // 큐가 가득 차 있으면 가장 오래된 데이터를 덮어씀
        queue->tail = (queue->tail + 1) % QUEUE_MAX_SIZE;
        queue->size--;
    }

    queue->buffer[queue->head] = value;
    queue->head = ((queue->head + 1) % QUEUE_MAX_SIZE);
    queue->size++;
}

// Queue에서 데이터 제거
boolean dequeue_queue(Queue *queue, AudioControlState *value)
{
    if (queue_isempty(queue)) {
        return FALSE; // 큐가 비어 있음
    }

    *value = queue->buffer[queue->tail];
    queue->tail = (queue->tail + 1) % QUEUE_MAX_SIZE;
    queue->size--;
    return TRUE;
}

/*********************************************************************************************************************/
